directory: /zmain/media/music
library: /zmain/media/music/musiclibrary.db
plugins: ftintitle fetchart embedart lyrics chroma convert mbsync edit
import:
    move: yes
convert:
    dest: /var/media/mp3
    auto_keep: yes
    copy_album_art: yes
    embed: yes
    never_convert_lossy_files: yes
